version: '3.9'

services:
  app:
    image: node:22
    container_name: web-scraper-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "echo 'App service lancé' && sleep infinity"
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: mongodb
    command: bash -c "echo 'MongoDB service lancé' && sleep infinity"
    ports:
      - '27017:27017'

  redis:
    image: redis:8
    container_name: redis
    command: bash -c "echo 'Redis service lancé' && sleep infinity"
    ports:
      - '6379:6379'

